;;;; Unit tests for FR-683 loop rotation.

(in-package :cl-cc/test)

(it-sequential "loop-rotate-fr683-while-becomes-bottom-guard"
  (let* ((insts (list (make-vm-const :dst :i :value 0)
                      (make-vm-const :dst :limit :value 8)
                      (make-vm-label :name "loop")
                      (make-vm-lt :dst :cond :lhs :i :rhs :limit)
                      (make-vm-jump-zero :reg :cond :label "exit")
                      (make-vm-add :dst :i :lhs :i :rhs :one)
                      (make-vm-jump :label "loop")
                      (make-vm-label :name "exit")
                      (make-vm-ret :reg :i)))
         (out (cl-cc/optimize::opt-pass-loop-rotate insts))
         (body-pos (%test-label-position out "loop_body"))
         (guard-pos (%test-label-position out "loop_guard"))
         (exit-pos (%test-label-position out "exit")))
    (expect body-pos :to-be-truthy)
    (expect guard-pos :to-be-truthy)
    (expect exit-pos :to-be-truthy)
    (expect (< body-pos guard-pos exit-pos) :to-be-truthy)
    (expect (typep (third out) 'cl-cc/vm::vm-jump) :to-be-truthy)
    (expect (cl-cc/vm::vm-label-name (third out)) :to-equal "loop_guard")
    (expect (some (lambda (inst)
             (and (typep inst 'cl-cc/vm::vm-jump)
                  (equal (cl-cc/vm::vm-label-name inst) "loop_body")))
           out) :to-be-truthy)))

(it-sequential "loop-rotate-fr683-skips-multiple-backedges"
  (let* ((insts (list (make-vm-label :name "loop")
                      (make-vm-lt :dst :cond :lhs :i :rhs :limit)
                      (make-vm-jump-zero :reg :cond :label "exit")
                      (make-vm-label :name "a")
                      (make-vm-jump :label "loop")
                      (make-vm-label :name "b")
                      (make-vm-jump :label "loop")
                      (make-vm-label :name "exit")
                      (make-vm-ret :reg :i)))
         (out (cl-cc/optimize::opt-pass-loop-rotate insts)))
    (expect (mapcar #'cl-cc/vm::instruction->sexp out) :to-equal (mapcar #'cl-cc/vm::instruction->sexp insts))))
