;;;; optimizer-store-analysis-tests.lisp — egraph, bswap/rotate, dead-store, SCCP, store-to-load
(in-package :cl-cc/test)


(it-sequential "egraph-pass-lowers-constant-subtraction"
  (let* ((i1 (cl-cc:make-vm-const :dst :r0 :value 7))
         (i2 (cl-cc:make-vm-sub   :dst :r1 :lhs :r0 :rhs :r0))
         (out (cl-cc/optimize:optimize-with-egraph (list i1 i2)))
         (r1  (find-if (lambda (inst)
                          (eq :r1 (ignore-errors (cl-cc/vm::vm-dst inst))))
                        out)))
    (expect r1 :to-be-truthy)))

(it-sequential "bswap-recognition-collapses-byte-swap-tree"
  (let* ((input (make-bswap-tree-instructions))
         (out   (cl-cc/optimize::opt-pass-bswap-recognition input)))
    (expect (= 1 (count-if (lambda (i) (typep i 'cl-cc/vm::vm-bswap)) out)) :to-be-truthy)
    (expect (some (lambda (i) (typep i 'cl-cc/vm::vm-logior)) out) :to-be-falsy)
    (expect (some (lambda (i) (typep i 'cl-cc/vm::vm-ash)) out) :to-be-falsy)))

(it-sequential "rotate-recognition-collapses-shift-or-tree"
  (let* ((c0  (make-vm-const :dst :r1 :value 8))
         (a0  (make-vm-ash   :dst :r2 :lhs :r0 :rhs :r1))
         (c1  (make-vm-const :dst :r3 :value -56))
         (a1  (make-vm-ash   :dst :r4 :lhs :r0 :rhs :r3))
         (o0  (make-vm-logior :dst :r5 :lhs :r2 :rhs :r4))
         (out (cl-cc/optimize::opt-pass-rotate-recognition (list c0 a0 c1 a1 o0))))
    (expect (= 1 (count-if (lambda (i) (typep i 'cl-cc/vm::vm-rotate)) out)) :to-be-truthy)
    (expect (some (lambda (i) (typep i 'cl-cc/vm::vm-logior)) out) :to-be-falsy)))

(it-sequential "dead-store-elim-cases overwritten-global"
  (destructuring-bind (make-case) (list (lambda ()
             (let* ((c1  (make-vm-const :dst :r0 :value 1))
                    (s1  (make-vm-set-global :name "g" :src :r0))
                    (c2  (make-vm-const :dst :r1 :value 2))
                    (s2  (make-vm-set-global :name "g" :src :r1))
                    (ret (make-vm-ret :reg :r1)))
               (list (list c1 s1 c2 s2 ret) (list s1) (list s2 c1 c2 ret)))))
    (destructuring-bind (instrs absent present) (funcall make-case)
    (let ((out (cl-cc/optimize::opt-pass-dead-store-elim instrs)))
      (dolist (inst absent)   (expect (member inst out) :to-be-falsy))
      (dolist (inst present)  (expect (member inst out) :to-be-truthy))))))

(it-sequential "dead-store-elim-cases keeps-live-read"
  (destructuring-bind (make-case) (list (lambda ()
             (let* ((c1  (make-vm-const :dst :r0 :value 1))
                    (s1  (make-vm-set-global :name "g" :src :r0))
                    (g1  (make-vm-get-global :dst :r2 :name "g"))
                    (c2  (make-vm-const :dst :r1 :value 2))
                    (s2  (make-vm-set-global :name "g" :src :r1))
                    (ret (make-vm-ret :reg :r2)))
               (list (list c1 s1 g1 c2 s2 ret) nil (list s1 g1 s2 ret)))))
    (destructuring-bind (instrs absent present) (funcall make-case)
    (let ((out (cl-cc/optimize::opt-pass-dead-store-elim instrs)))
      (dolist (inst absent)   (expect (member inst out) :to-be-falsy))
      (dolist (inst present)  (expect (member inst out) :to-be-truthy))))))

(it-sequential "dead-store-elim-cases slot-overwrite-alias"
  (destructuring-bind (make-case) (list (lambda ()
             (let* ((obj  (make-vm-cons :dst :r0 :car-src :r8 :cdr-src :r9))
                    (obj2 (make-vm-move :dst :r3 :src :r0))
                    (c1   (make-vm-const :dst :r1 :value 10))
                    (w1   (cl-cc:make-vm-slot-write :obj-reg :r0 :slot-name 'x :value-reg :r1))
                    (c2   (make-vm-const :dst :r2 :value 20))
                    (w2   (cl-cc:make-vm-slot-write :obj-reg :r3 :slot-name 'x :value-reg :r2))
                    (ret  (make-vm-ret :reg :r2)))
                (list (list obj obj2 c1 w1 c2 w2 ret)
                      (list w1)
                      (list obj obj2 c1 c2 w2 ret)))))
    (destructuring-bind (instrs absent present) (funcall make-case)
    (let ((out (cl-cc/optimize::opt-pass-dead-store-elim instrs)))
      (dolist (inst absent)   (expect (member inst out) :to-be-falsy))
      (dolist (inst present)  (expect (member inst out) :to-be-truthy))))))

(it-sequential "sccp-eliminates-constant-branch-block"
  (let* ((start (make-vm-label :name "start"))
         (cond  (make-vm-const :dst :r0 :value 1))
         (br    (make-vm-jump-zero :reg :r0 :label "else"))
         (thenl (make-vm-label :name "then"))
         (thenv (make-vm-const :dst :r1 :value 10))
         (jmp   (make-vm-jump :label "end"))
         (elsel (make-vm-label :name "else"))
         (elsev (make-vm-const :dst :r1 :value 20))
         (endl  (make-vm-label :name "end"))
         (ret   (make-vm-ret :reg :r1))
         (out   (cl-cc/optimize::opt-pass-sccp (list start cond br thenl thenv jmp elsel elsev endl ret))))
    (expect (member elsel out) :to-be-falsy)
    (expect (member elsev out) :to-be-falsy)
    (expect (some (lambda (i) (and (typep i 'cl-cc/vm::vm-const)
                                         (eq (cl-cc/vm::vm-dst i) :r1)
                                         (eql (cl-cc/vm::vm-value i) 10)))
                        out) :to-be-truthy)))

(it-sequential "store-to-load-forward-cases global-direct"
  (destructuring-bind (make-case) (list (lambda ()
             (let* ((c1  (make-vm-const :dst :r0 :value 1))
                    (s1  (make-vm-set-global :name "g" :src :r0))
                    (g1  (make-vm-get-global :dst :r1 :name "g"))
                    (ret (make-vm-ret :reg :r1)))
               (list (list c1 s1 g1 ret) g1 :r1 :r0))))
    (destructuring-bind (instrs read-instr expected-dst expected-src) (funcall make-case)
    (let ((out (cl-cc/optimize::opt-pass-store-to-load-forward instrs)))
      (expect (member read-instr out :test #'eq) :to-be-falsy)
      (expect (some (lambda (i)
                           (and (typep i 'cl-cc/vm::vm-move)
                                (eq (cl-cc:vm-move-dst i) expected-dst)
                                (eq (cl-cc:vm-move-src i) expected-src)))
                         out) :to-be-truthy)))))

(it-sequential "store-to-load-forward-cases global-same-dst"
  (destructuring-bind (make-case) (list (lambda ()
             (let* ((c1  (make-vm-const :dst :r0 :value 1))
                    (s1  (make-vm-set-global :name "g" :src :r0))
                    (g1  (make-vm-get-global :dst :r0 :name "g"))
                    (ret (make-vm-ret :reg :r0)))
               (list (list c1 s1 g1 ret) g1 :r0 :r0))))
    (destructuring-bind (instrs read-instr expected-dst expected-src) (funcall make-case)
    (let ((out (cl-cc/optimize::opt-pass-store-to-load-forward instrs)))
      (expect (member read-instr out :test #'eq) :to-be-falsy)
      (expect (some (lambda (i)
                           (and (typep i 'cl-cc/vm::vm-move)
                                (eq (cl-cc:vm-move-dst i) expected-dst)
                                (eq (cl-cc:vm-move-src i) expected-src)))
                         out) :to-be-truthy)))))

(it-sequential "store-to-load-forward-cases slot-direct"
  (destructuring-bind (make-case) (list (lambda ()
             (let* ((obj (make-vm-const :dst :r0 :value 42))
                    (val (make-vm-const :dst :r1 :value 99))
                    (w   (cl-cc:make-vm-slot-write :obj-reg :r0 :slot-name 'x :value-reg :r1))
                    (r   (cl-cc:make-vm-slot-read :dst :r2 :obj-reg :r0 :slot-name 'x))
                    (ret (make-vm-ret :reg :r2)))
               (list (list obj val w r ret) r :r2 :r1))))
    (destructuring-bind (instrs read-instr expected-dst expected-src) (funcall make-case)
    (let ((out (cl-cc/optimize::opt-pass-store-to-load-forward instrs)))
      (expect (member read-instr out :test #'eq) :to-be-falsy)
      (expect (some (lambda (i)
                           (and (typep i 'cl-cc/vm::vm-move)
                                (eq (cl-cc:vm-move-dst i) expected-dst)
                                (eq (cl-cc:vm-move-src i) expected-src)))
                         out) :to-be-truthy)))))

(it-sequential "store-to-load-forward-cases slot-same-dst"
  (destructuring-bind (make-case) (list (lambda ()
             (let* ((obj (make-vm-const :dst :r0 :value 42))
                    (val (make-vm-const :dst :r1 :value 99))
                    (w   (cl-cc:make-vm-slot-write :obj-reg :r0 :slot-name 'x :value-reg :r1))
                    (r   (cl-cc:make-vm-slot-read :dst :r1 :obj-reg :r0 :slot-name 'x))
                    (ret (make-vm-ret :reg :r1)))
               (list (list obj val w r ret) r :r1 :r1))))
    (destructuring-bind (instrs read-instr expected-dst expected-src) (funcall make-case)
    (let ((out (cl-cc/optimize::opt-pass-store-to-load-forward instrs)))
      (expect (member read-instr out :test #'eq) :to-be-falsy)
      (expect (some (lambda (i)
                           (and (typep i 'cl-cc/vm::vm-move)
                                (eq (cl-cc:vm-move-dst i) expected-dst)
                                (eq (cl-cc:vm-move-src i) expected-src)))
                         out) :to-be-truthy)))))

(it-sequential "store-to-load-forward-cases slot-through-moved-alias"
  (destructuring-bind (make-case) (list (lambda ()
             (let* ((obj  (make-vm-cons :dst :r0 :car-src :r8 :cdr-src :r9))
                    (obj2 (make-vm-move :dst :r3 :src :r0))
                    (val  (make-vm-const :dst :r1 :value 99))
                    (w    (cl-cc:make-vm-slot-write :obj-reg :r0 :slot-name 'x :value-reg :r1))
                    (r    (cl-cc:make-vm-slot-read :dst :r2 :obj-reg :r3 :slot-name 'x))
                    (ret  (make-vm-ret :reg :r2)))
               (list (list obj obj2 val w r ret) r :r2 :r1))))
    (destructuring-bind (instrs read-instr expected-dst expected-src) (funcall make-case)
    (let ((out (cl-cc/optimize::opt-pass-store-to-load-forward instrs)))
      (expect (member read-instr out :test #'eq) :to-be-falsy)
      (expect (some (lambda (i)
                           (and (typep i 'cl-cc/vm::vm-move)
                                (eq (cl-cc:vm-move-dst i) expected-dst)
                                (eq (cl-cc:vm-move-src i) expected-src)))
                         out) :to-be-truthy)))))
