;;;; packages/emit/tests/mlir-tests.lisp

(in-package :cl-cc/test)


(it-sequential "mlir-lowers-clcc-dialect-arithmetic-call-return-and-branch"
  (let* ((fn (mir-make-function :mlir-add-or-sub))
         (entry (mirf-entry fn))
         (then-block (mir-new-block fn :label :then))
         (else-block (mir-new-block fn :label :else))
         (lhs (mir-new-value fn :name :lhs :type :integer))
         (rhs (mir-new-value fn :name :rhs :type :integer))
         (condv (mir-new-value fn :name :cond :type :boolean))
         (sum (mir-new-value fn :name :sum :type :integer))
         (product (mir-new-value fn :name :product :type :integer))
         (called (mir-new-value fn :name :called :type :integer))
         (diff (mir-new-value fn :name :diff :type :integer)))
    (setf (mirf-params fn) (list lhs rhs))
    (mir-add-succ entry then-block)
    (mir-add-succ entry else-block)
    (mir-emit entry :const :dst condv :srcs (list (make-mir-const :value 1 :type :boolean)))
    (mir-emit entry :branch :srcs (list condv then-block else-block))
    (mir-emit then-block :add :dst sum :srcs (list lhs rhs) :type :integer)
    (mir-emit then-block :mul :dst product :srcs (list sum (make-mir-const :value 2 :type :integer)) :type :integer)
    (mir-emit then-block :call :dst called
              :srcs (list (make-mir-const :value :external-inc :type :function) product)
              :type :integer)
    (mir-emit then-block :ret :srcs (list called))
    (mir-emit else-block :sub :dst diff :srcs (list rhs lhs) :type :integer)
    (mir-emit else-block :ret :srcs (list diff))
    (let ((mlir (cl-cc/emit:emit-mlir fn :name "fr712-real")))
      (expect (search "module @fr712_real {" mlir) :to-be-truthy)
      (expect (search "func.func @mlir_add_or_sub(%arg0: i64, %arg1: i64) -> i64" mlir) :to-be-truthy)
      (expect (search "%reg2 = arith.constant 1 : i1" mlir) :to-be-truthy)
      (expect (search "cf.cond_br %reg2, ^then, ^else" mlir) :to-be-truthy)
      (expect (search "%reg3 = arith.addi %arg0, %arg1 : i64" mlir) :to-be-truthy)
      (expect (search "arith.constant 2 : i64" mlir) :to-be-truthy)
      (expect (search "%reg4 = arith.muli %reg3" mlir) :to-be-truthy)
      (expect (search "%reg5 = func.call @external_inc(%reg4) : (i64) -> i64" mlir) :to-be-truthy)
      (expect (search "func.func private @external_inc(i64) -> i64" mlir) :to-be-truthy)
      (expect (search "%reg6 = arith.subi %arg1, %arg0 : i64" mlir) :to-be-truthy)
      (expect (search "func.return %reg5 : i64" mlir) :to-be-truthy)
      (expect (search "TODO" mlir) :to-be-falsy)
      (expect (search "bridge-only" mlir) :to-be-falsy))))

(it-sequential "mlir-lowers-void-call-and-return"
  (let* ((fn (mir-make-function :mlir-void-call))
         (entry (mirf-entry fn)))
    (mir-emit entry :call
              :srcs (list (make-mir-const :value :notify :type :function)
                          (make-mir-const :value 7 :type :integer))
              :type :void)
    (mir-emit entry :ret)
    (let ((mlir (cl-cc/emit:emit-mlir fn :name "fr712-void")))
      (expect (search "func.func private @notify(i64)" mlir) :to-be-truthy)
      (expect (search "func.call @notify" mlir) :to-be-truthy)
      (expect (search ": (i64) -> ()" mlir) :to-be-truthy)
      (expect (search "func.return" mlir) :to-be-truthy)
      (expect (search "-> none" mlir) :to-be-falsy))))

(it-sequential "mlir-unsupported-phi-signals-error"
  (let* ((fn (mir-make-function :mlir-phi))
         (entry (mirf-entry fn))
         (merge (mir-new-block fn :label :merge))
         (value (mir-new-value fn :type :integer)))
    (mir-add-succ entry merge)
    (mir-emit entry :jump :srcs (list merge))
    (mir-emit merge :phi :dst value :srcs (list (cons entry (make-mir-const :value 1 :type :integer))))
    (mir-emit merge :ret :srcs (list value))
    (signals error (cl-cc/emit:emit-mlir fn :name "fr712-phi"))))

(it-sequential "mlir-capabilities-describe-clcc-lowering-patterns"
  (let ((caps (cl-cc/emit:mlir-bridge-capabilities)))
    (expect (member :defined-dialect caps) :to-be-truthy)
    (expect (search "CLCC.ADD" (format nil "~S" caps)) :to-be-truthy)
    (expect (search "ARITH.ADDI" (format nil "~S" caps)) :to-be-truthy)
    (expect (search "FUNC.CALL" (format nil "~S" caps)) :to-be-truthy)
    (expect (search "FUNC.RETURN" (format nil "~S" caps)) :to-be-truthy)
    (expect (member :bridge-only caps) :to-be-falsy)))
