;;;; cli/src/handlers-advanced.lisp — Advanced CLI Subcommand Handlers
;;; Generated by splitting handlers.lisp into domain-specific modules.

(in-package :cl-cc/cli)

(defun %do-check (parsed)
  "Handle the `cl-cc check' subcommand using PARSED arguments.

Reads the required source file, runs type inference in warning or strict mode,
prints the inferred type when available, and reports structured diagnostics
with a source caret and type trace on failure."
  (let* ((file (%required-file-arg parsed "check"))
         (strict (flag parsed "--strict"))
         (verbose (flag parsed "--verbose"))
         (mode (if strict :strict :warn))
         (source (%read-command-source file)))
    (when verbose
      (format *error-output* "; cl-cc check: ~A  mode=~A~%" file mode))
    (%with-cli-timeout (parsed "check")
      (handler-case
          (progn
            (multiple-value-bind (result inferred-type)
                (run-string-typed source :mode mode)
              (declare (ignore result))
              (if inferred-type
                  (format t "~A~%" (type-to-string inferred-type))
                  (format t "<no type inferred>~%")))
            (%cli-exit 0))
        (error (e)
          (let* ((message (princ-to-string e))
                 (location (and (typep e 'cl-cc/ast:ast-compilation-error)
                                (cl-cc/ast:ast-error-location e)))
                 (line-number nil)
                 (column-number nil))
            (multiple-value-setq (line-number column-number)
              (%extract-line-column-from-location location))
            (let* ((line-text (%source-line-at source line-number))
                   (snippet (cl-cc/optimize:opt-build-diagnostic-caret-line
                             line-text
                             (or column-number 1)))
                   (trace (cl-cc/optimize:opt-format-type-trace
                           (list message))))
              (format *error-output* "~A~%"
                      (cl-cc/optimize:opt-format-diagnostic-reason
                       "type-check"
                       "failed"
                       message))
              (when location
                (format *error-output* "at ~A~%" location))
              (format *error-output* "~A~%" snippet)
              (format *error-output* "~A~%" trace)))
            (%cli-exit 1))))))

(defun %do-doc (parsed)
  "API documentation generation: FR-321. Extract docstrings to Markdown."
  (%with-cli-timeout (parsed "doc")
    (%with-cli-error-handler
      (let ((file (%required-existing-file-arg parsed "doc"))
            (output-path (flag-or parsed "--output" "-o")))
        (if output-path
            (progn
              (generate-api-docs file :output-path output-path)
              (format t "Documentation generated: ~A~%" output-path))
            (write-string (generate-api-docs file) *standard-output*))))))

(defun %do-show-types (parsed)
  "Type signature display: FR-904. Show inferred types."
  (%with-cli-timeout (parsed "show-types")
    (%with-cli-error-handler
      (let ((file (%required-existing-file-arg parsed "show-types")))
        (multiple-value-bind (result inferred-type)
            (run-string-typed (%read-command-source file) :mode :warn)
          (declare (ignore result))
          (unless inferred-type
            (error "No type was inferred for ~A" file))
          (format t "~A~%" (type-to-string inferred-type)))))))

(defun %do-abi-dump (parsed)
  "ABI dump: FR-777. Dump public API surface."
  (%with-cli-timeout (parsed "abi-dump")
    (%with-cli-error-handler
      (let ((path (%required-file-arg parsed "abi-dump")))
        (cl-cc/compile:dump-abi-manifest path)
        (unless (probe-file path)
          (error "ABI manifest was not written: ~A" path))
        (format t "ABI manifest written: ~A~%" path)))))

(defun %read-abi-manifest (path)
  "Read and validate the plist format emitted by DUMP-ABI-MANIFEST."
  (with-open-file (stream path :direction :input)
    (let ((manifest (read stream nil :eof)))
      (when (eq manifest :eof)
        (error "ABI manifest is empty: ~A" path))
      (unless (and (listp manifest)
                   (getf manifest :version)
                   (or (null (getf manifest :exports))
                       (listp (getf manifest :exports)))
                   (or (null (getf manifest :struct-layouts))
                       (listp (getf manifest :struct-layouts)))
                   (integerp (getf manifest :checksum)))
        (error "Invalid ABI manifest: ~A" path))
      manifest)))

(defun %do-abi-check (parsed)
  "ABI compatibility check: FR-777. Compare ABI manifests."
  (%with-cli-timeout (parsed "abi-check")
    (%with-cli-error-handler
      (let ((paths (parsed-args-positional parsed)))
        (unless (= 2 (length paths))
          (%quit-command-usage-error "abi-check"
                                     "'abi-check' requires old and new manifest files."))
        (let ((issues (cl-cc/compile:check-abi-compatibility
                       (%read-abi-manifest (first paths))
                       (%read-abi-manifest (second paths)))))
          (if issues
              (progn
                (format *error-output* "ABI incompatibility: ~{~A~^, ~}~%" issues)
                (%cli-exit 1))
              (format t "ABI check: compatible.~%")))))))

(defun %do-demangle (parsed)
  "Name demangling: FR-776. Demangle C++ ABI symbols."
  (%with-cli-timeout (parsed "demangle")
    (%with-cli-error-handler
      (let ((name (or (car (parsed-args-positional parsed))
                      (%quit-command-usage-error
                       "demangle"
                       "'demangle' requires a mangled name argument."))))
        (format t "~A~%" (cl-cc/compile:demangle-name name))))))

(defun %run-wasm-tool-command (tool args unavailable-message)
  "Run TOOL with ARGS, printing stdout, and signal failures."
  (if (cl-cc/codegen:wasm-tool-available-p tool)
      (let ((out (cl-cc/codegen:wasm-run-tool-to-string (cons tool args))))
        (if (stringp out)
            (write-string out)
            (error "~A failed" tool)))
      (error "~A" unavailable-message)))

(defun %do-disasm (parsed)
  "FR-322: Disassemble a Wasm module using wabt tools when available."
  (%with-cli-timeout (parsed "disasm")
    (%with-cli-error-handler
      (let ((file (%required-existing-file-arg parsed "disasm")))
        (cond
          ((flag parsed "--decompile")
           (%run-wasm-tool-command "wasm-decompile" (list file)
                                   "wasm-decompile is not available in this environment."))
          ((flag parsed "--wat")
           (%run-wasm-tool-command "wasm2wat" (list file)
                                   "wasm2wat is not available in this environment."))
          (t
           (%run-wasm-tool-command "wasm-objdump" (list "-d" file)
                                   "wasm-objdump is not available in this environment.")))))))

(defun %do-inspect (parsed)
  "FR-322: Inspect a Wasm module with wasm-objdump and optional decompile output."
  (%with-cli-timeout (parsed "inspect")
    (%with-cli-error-handler
      (let ((file (%required-existing-file-arg parsed "inspect")))
        (%run-wasm-tool-command "wasm-objdump" (list "-x" "-d" file)
                                "wasm-objdump is not available in this environment.")
        (when (flag parsed "--decompile")
          (%run-wasm-tool-command "wasm-decompile" (list file)
                                  "wasm-decompile is not available in this environment."))))))

(defun %do-update (parsed)
  "Package update: FR-813/FR-1039. Update Quicklisp deps and qlfile.lock."
  (let ((package (car (parsed-args-positional parsed))))
    (%with-cli-error-handler
      (%with-cli-timeout (parsed "update")
        (format t "Updating ~A...~%" (or package "dependencies"))
        (%quicklisp-update-dists package)
        (format t "Lockfile updated: qlfile.lock~%"))
      (%cli-exit 0))))

;;; ─────────────────────────────────────────────────────────────────────────
;;; FR-361: Dependency Graph Visualization
;;; ─────────────────────────────────────────────────────────────────────────

(defun %do-dep-graph (parsed)
  "Dependency graph: FR-361. Generate ASDF dependency graph as DOT."
  (%with-cli-timeout (parsed "dep-graph")
    (%with-cli-error-handler
      (%handle-dep-graph parsed))))
