;;;; cli/src/handlers-utils.lisp — Shared CLI Handler Utilities
;;; Generated by splitting handlers.lisp into domain-specific modules.

(in-package :cl-cc/cli)

;; `compile-opts` is defined in main-dump.lisp, which loads after this file.
;; Prevent premature inlining warnings for its accessors during compile-file.
(declaim (notinline compile-opts-flamegraph-path
                      compile-opts-profile
                      compile-opts-debug-info
                      compile-opts-sanitize
                      compile-opts-lto
                      compile-opts-eh-model
                      compile-opts-incremental
                      compile-opts-perf-map
                      compile-opts-parallel
                      compile-opts-pgo-generate-path
                      compile-opts-pgo-use-path
                      compile-opts-block-compile
                      compile-opts-spectre-mitigations
                      compile-opts-jit-cache-stats
                      compile-opts-trace-json-path
                     compile-opts-trace-emit
                     compile-opts-retpoline
                     compile-opts-stack-protector
                      compile-opts-shadow-stack
                      compile-opts-deterministic
                      compile-opts-build-id
                      compile-opts-asan
                     compile-opts-msan
                     compile-opts-tsan
                     compile-opts-ubsan
                       compile-opts-hwasan
                        compile-opts-werror
                        ;; FR-276/241/153: new optimization/tracing flags
                        compile-opts-opt-level
                        compile-opts-trace-macros
                        compile-opts-memoize-macros
                        compile-opts-gc-min-heap
                        compile-opts-gc-max-heap))

(defun %call-with-runtime-sanitizer-flags (opts thunk &rest args)
  "Execute THUNK with runtime sanitizer toggles derived from OPTS."
  (let ((cl-cc/runtime:*rt-asan-enabled* (not (null (compile-opts-asan opts))))
        (cl-cc/runtime:*rt-msan-enabled* (not (null (compile-opts-msan opts))))
        (cl-cc/runtime:*rt-tsan-enabled* (not (null (compile-opts-tsan opts))))
        (cl-cc/runtime:*rt-hwasan-enabled* (not (null (compile-opts-hwasan opts))))
        (cl-cc/runtime:*rt-ubsan-enabled* (not (null (compile-opts-ubsan opts))))
        (cl-cc/runtime:*gc-young-size-words*
         (or (compile-opts-gc-min-heap opts)
             cl-cc/runtime:*gc-young-size-words*))
        (cl-cc/runtime:*gc-old-size-words*
         (or (compile-opts-gc-max-heap opts)
             cl-cc/runtime:*gc-old-size-words*))
        (cl-cc/parse:*werror-p* (not (null (compile-opts-werror opts)))))
    (apply thunk args)))

;;; ─── Watch mode + hot-reload (FR-808 / FR-916/917) ──────────────────────────
;;;
;;; The run and repl handlers record the source of each executed file and, when
;;; --watch is given, poll the file's write-date to recompile and re-run it on
;;; every save. One VM state is reused across reloads so global definitions
;;; persist — true hot-reload, not a fresh process per edit. Previously these
;;; entry points were referenced by the handlers but never defined, so every
;;; `cl-cc run` crashed with "%RECORD-HOT-RELOAD-SOURCE is undefined".

(defvar *hot-reload-records* (make-hash-table :test #'equal)
  "In-memory metadata for watch-mode sources and their last reload result.")

(defun %file-write-date-or-nil (path)
  "Return PATH's write date, or NIL if it cannot be probed."
  (ignore-errors
    (when path
      (file-write-date path))))

(defun %hot-reload-record-key (path)
  (let ((truename (ignore-errors (truename path))))
    (namestring (or truename path))))

(defun %record-hot-reload-source (path source result)
  "Record SOURCE metadata for PATH and return RESULT unchanged."
  (setf (gethash (%hot-reload-record-key path) *hot-reload-records*)
        (list :source source :result result))
  result)

(defun %watch-file-poll (path vm-state &key (interval 1) language)
  "Poll PATH and hot-reload changed definitions into VM-STATE."
  (let ((language (or language (%detect-language path nil)))
        (last-write-date (%file-write-date-or-nil path)))
    (format *error-output* "; cl-cc watch: polling ~A every ~A second~:P~%" path interval)
    (force-output *error-output*)
    (loop
      (sleep interval)
      (let ((write-date (%file-write-date-or-nil path)))
        (when (and write-date
                   (or (null last-write-date) (> write-date last-write-date)))
          (setf last-write-date write-date)
          (handler-case
              (let ((cl-cc/repl::*repl-vm-state* vm-state))
                (let* ((source (%strip-shebang-line (%read-file path)))
                       (result (cl-cc:run-string-repl source :language language)))
                  (%record-hot-reload-source path source result)
                  (format *error-output* "; cl-cc watch: hot-reloaded ~A => ~S~%" path result)
                  (force-output *error-output*)))
            (error (e)
              (format *error-output* "; cl-cc watch: reload failed: ~A~%" e)
              (force-output *error-output*))))))))

(defun %start-watch-file-poll-thread (path vm-state &optional language)
  "Start a background polling watcher for PATH."
  (sb-thread:make-thread
   (lambda ()
     (let ((cl-cc/repl::*repl-vm-state* vm-state))
       (%watch-file-poll path vm-state :language language)))
   :name (format nil "cl-cc hot reload watcher: ~A" path)))
